"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv, find_dotenv
from datetime import timedelta

load_dotenv(find_dotenv())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

raw_allowed_hosts = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = raw_allowed_hosts.split(",") if raw_allowed_hosts else []

raw_allowed_cors = os.getenv("ALLOWED_CORS", "http://localhost")
ALLOWED_CORS = raw_allowed_cors.split(",") if raw_allowed_cors else []

CSRF_TRUSTED_ORIGINS = [
    "https://al.lchappuis.fr",
]


DATA_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024  # 200 Mo
FILE_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024  # 200 Mo


# CORS_ALLOWED_ORIGINS = ALLOWED_CORS
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = ALLOWED_CORS

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "rest_framework",
    "corsheaders",
    "channels",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "EXCEPTION_HANDLER": "core.exceptions.handler.custom_exception_handler",
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"
ASGI_APPLICATION = "backend.asgi.application"

# Database Configuration
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Check if we should use local SQLite database
USE_LOCAL_DB = os.getenv("USE_LOCAL_DB", "False") == "True"

# Cache the database mode detection to avoid repeated checks
_unused_db_check_cache_file = BASE_DIR / ".db_mode_cache"


def _test_mysql_connection():
    """Test if MySQL server is reachable."""
    if USE_LOCAL_DB:
        return False

    import socket

    host = os.getenv("DATABASE_HOST", "localhost")
    port = int(os.getenv("DATABASE_PORT", "3306"))

    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(3)  # 3 second timeout for connection test
        result = sock.connect_ex((host, port))
        sock.close()
        return result == 0
    except Exception:
        return False


# Determine which database to use
_mysql_available = _test_mysql_connection()

# Track if we've already shown the warning (avoid duplicate messages)
_warning_shown = os.environ.get("_DB_WARNING_SHOWN", "")

if USE_LOCAL_DB or not _mysql_available:
    if not USE_LOCAL_DB and not _mysql_available and not _warning_shown:
        os.environ["_DB_WARNING_SHOWN"] = "1"
        sys.stderr.write(
            "\n" + "=" * 60 + "\n"
            "WARNING: Cannot connect to remote MySQL database.\n"
            f"Host: {os.getenv('DATABASE_HOST')}:{os.getenv('DATABASE_PORT')}\n"
            "Falling back to local SQLite database.\n"
            "Set USE_LOCAL_DB=True in .env to suppress this warning.\n"
            "=" * 60 + "\n\n"
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    DATABASE_MODE = "sqlite"
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DATABASE_NAME"),
            "USER": os.getenv("DATABASE_USERNAME"),
            "PASSWORD": os.getenv("DATABASE_PASSWORD"),
            "HOST": os.getenv("DATABASE_HOST"),
            "PORT": os.getenv("DATABASE_PORT", "3306"),
            "OPTIONS": {
                "connect_timeout": 30,
                "read_timeout": 60,
                "write_timeout": 60,
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            },
            "CONN_MAX_AGE": 60,  # Keep connections alive for 60 seconds
            "CONN_HEALTH_CHECKS": True,  # Enable connection health checks
        }
    }
    DATABASE_MODE = "mysql"


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv("REDIS_HOST", "localhost"), 6379)],
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{os.getenv('REDIS_HOST', 'localhost')}:6379/1",
        "TIMEOUT": 60 * 60 * 24 * 7,
    }
}

# Media proxy tuning (backend-served photos)
MEDIA_ALLOWED_WIDTHS = [240, 480, 960, 1920]  # bounds cache cardinality
MEDIA_MAX_DIMENSION = 1920  # auto-downscale threshold for full-size requests
MEDIA_RECOMPRESS_BYTES = 500 * 1024  # recompress originals bigger than this
MEDIA_CACHE_MAX_BYTES = 5 * 1024 * 1024  # never cache blobs bigger than this
MEDIA_WEBP_QUALITY = 80


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/dj/static/"
STATIC_ROOT = BASE_DIR / "static"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.db.backends": {
            "level": "WARNING",
            "handlers": ["console"],
        },
        "websocket": {
            "level": "DEBUG" if DEBUG else "INFO",
            "handlers": ["console"],
        },
    },
}
